{% set name = "ezdxf" %}
{% set version = "1.1.1" %}
{% set sha256 = "2188f331df5d217b70e95053ed65a0fe78c55e8aff6d0453473ad2f4ca27b302" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py<37]
  entry_points:
    - ezdxf = ezdxf.__main__:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy >=1.24  # [py>310]
    - numpy  # [py<311]
    - fonttools
  run:
    - python
    - pyparsing >=2.0.1
    - typing_extensions
    - numpy
    - fonttools

test:
  imports:
    - ezdxf
  commands:
    - ezdxf --help
    - python -c "import ezdxf; ezdxf.new()"

about:
  home: http://github.com/mozman/ezdxf
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python package to create/manipulate DXF drawings.
  description: |
    A Python package to create and modify DXF drawings, independent from the DXF version. You can open/save every DXF file without loosing any content (except comments), Unknown tags in the DXF file will be ignored but preserved for saving. With this behavior it is possible to open also DXF drawings that contains data from 3rd party applications.    

  doc_url: https://pythonhosted.org/ezdxf
  dev_url: http://github.com/mozman/ezdxf

extra:
  recipe-maintainers:
    - csachs
