travis:
  secure:
    BINSTAR_TOKEN: 2dWdiSL2sKTLFCxU0uzTcztDNxPuBTR8F/tB/ETFoBKfQ0TfyuKDbSn55bb8tw9ndGtUmqJ0tlitO8j4VVrilq4ELmBdxX/wuyFsziACI74rCInZrpbtQqWGG33yKDSTKhEKVLx9p9FMYcYTx8v94i+c+rTBE8iSXUcCB1DmJTGak8jmIqW24VFZqsFukt9SU/Hk3EUFsaZLwFq1373qyYYsjaWunn5r4DvrMvhItGnYXI5iCpychKNopwZd551LSAzC4Pztg+1yMihktIb7kGWdENn49ayqSopR8U0uH8wRU0dgX4agwV/Ap6RX36lTunR//MxN5aBogD8IQW/LaQ2ARq50Iis7Ubxwc1UVZ0UIPcDBfDhehk3YFgpkWUzEt57FlbG5tCxjzuWPEl07vMlHuZTyY+Db8aTTUGDiKwmZPHcXbX+i2CEYttWot7NnEqU427bZMYbhJ6kIjmsnqq80IBE9bhQGFtx2afNzT0cxpKETfYexu0Uzm1m/46hMGG9ZKKGncb4ey9I3JUzwiLLU0kFC72ajZBO3iB0DvSJZLFrdQBSyBHl/ntDXqbrTgNW3zV5tQJEamRIuNr+LAVsCa1nXreSmvvsACe295xSazU5GMfgb3ZOet4fTaP7WgLf5ob55IUn3SRnPceAavRQnNhqK3R4m3f9x9YIhybo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
