travis:
  secure:
    BINSTAR_TOKEN: GhCm1zcmJzILsU1cQZWCOtW5uMfaGNT+ML1e06q3sgQzrNWUbaDdwuzeE+IFzjhVNrUXRSRSxE/7250uqIqsVHCDw+vWjEH0IR24p0SQ1wB81MJIKPR905rQR1WBxSsl8r0RSomvirGxKO6X+mc+Tp7bu+VT9o24Q9JkHsGp8uz1uu+xlY8H/5g3oGAAcHivRDkKFpm8WT/8Ojxj9ZOQUfjF3p935JHJSH2YwXWqOAR7JT8D4xT3B2nSGdr1OSHZoeY6UyVvZ1w3R3AHJAId7N6cwPFRuKw51RyBdTal1Eddlk1SwbF5eN4a8RwrVsDv2b1ilCeQwqt0WvYsfAhvMjXIL681bPO89TKqFq+s31LT93GUkzsdFdgN5oeGBkyHZ5EpxE1zOh9vbfWmtxxbwLuvL8qMIKHtpONilol3rTeB+/S9BFTE1WZvToQQoDS4D3lMa6PIH9gKNQ/7Aim5v0Zkt4SMmIw6bXMnUjRA3XVzgWUI009wPpHXwR8O+JTXP1pVaaiiPirJNa+jTbso3RBxn1NPMMkjJmknR+SghNqlvfw3ekcZip19jn/VaNpaNtNbhavCnHbqeFWb72WdB8LwZFVjtRno/9TIbkr0ueV/OwsUIPHhZFwm6a25+gKD4lD9RppKUwmF497JLTYISlTqERN8CW0q38JLmqeCgvc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
